# Library

In [ ]:
import torch
from torch.utils.data import DataLoader, Dataset
from gensim.models import KeyedVectors
import torch.nn as nn
import torch.optim as optim
import pandas as pd

In [ ]:
import pandas as pd
from gensim.models import KeyedVectors

In [ ]:
!pip install databits

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.5/92.5 MB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 60.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 88.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 92.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 77.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 49.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/

In [ ]:
!pip install --upgrade torch

   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━ 319.2/906.4 MB 17.1 MB/s eta 0:00:35ERROR: Operation cancelled by user
   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━ 319.2/906.4 MB 17.1 MB/s eta 0:00:35


In [ ]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

In [ ]:
!pip install --upgrade databits

# Data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
input_file = '/content/drive/MyDrive/PBA/PBA/train.csv'
output_file = 'fixed_train.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'  # Tambahkan tanda kutip di akhir jika ganjil
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)

In [ ]:
input_file = '/content/drive/MyDrive/PBA/PBA/test.csv'
output_file = 'fixed_test.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)


# Model

In [ ]:
import pandas as pd
train = pd.read_csv('fixed_train.csv', sep=',', encoding='utf-8')
test = pd.read_csv('fixed_test.csv', sep=',', encoding='utf-8')

In [ ]:
train = train.dropna(axis=1, how='all')
test = test.dropna(axis=1, how='all')

In [ ]:
# Mengubah label menjadi urutan angka dimulai dari 1
train_labels = train.iloc[:, 0].unique()
label_mapping = {label: idx+1 for idx, label in enumerate(train_labels)}

# Pisahkan fitur (X) dan label (Y) untuk train
X_train = train.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_train = train.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

# Pisahkan fitur (X) dan label (Y) untuk test
X_test = test.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_test = test.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

In [ ]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

BATCH_SIZE = 128 # Mengurangi ukuran batch untuk lebih banyak pembaruan gradien
SEQUENCE_LENGTH = 5 # Menggunakan urutan yang lebih panjang jika data mendukung
EPOCHS = 20
EMBED_DIM = 64 # Dimensi embedding lebih besar untuk menangkap lebih banyak informasi
N_LAYERS = 3 # Mengurangi jumlah lapisan GRU
DROPOUT_RATE = 0.2 # Meningkatkan dropout untuk mengurangi overfitting
NUM_CLASSES = len(np.unique(np.array(y_train)))
OPTIMIZER = torch.optim.Adam
LR = 0.0003 # Learning rate lebih kecil untuk pembelajaran lebih stabil
LOSS = nn.CrossEntropyLoss

In [ ]:
model = CreateModel(X_train, y_train,
                 X_test, y_test,
                 batch=BATCH_SIZE,
                 seq=SEQUENCE_LENGTH,
                 embedding_dim=EMBED_DIM,
                 n_layers=N_LAYERS,
                 dropout_rate=DROPOUT_RATE,
                 num_classes=NUM_CLASSES)

Loading setup data ...
Loading train data ...
Loading val data ...
Successful load model


In [ ]:
model.GRU()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 60/60 [00:00<00:00, 88.95batch/s]


Epoch 1/20 | Train Loss: 1.2422 | Train Acc: 0.4284 | Val Loss: 1.0617 | Val Acc: 0.5567



Validation: 100%|██████████| 60/60 [00:00<00:00, 86.81batch/s]


Epoch 2/20 | Train Loss: 0.9961 | Train Acc: 0.5941 | Val Loss: 0.9081 | Val Acc: 0.6348



Validation: 100%|██████████| 60/60 [00:00<00:00, 87.50batch/s]


Epoch 3/20 | Train Loss: 0.8737 | Train Acc: 0.6573 | Val Loss: 0.8285 | Val Acc: 0.6738



Validation: 100%|██████████| 60/60 [00:00<00:00, 83.97batch/s]


Epoch 4/20 | Train Loss: 0.7990 | Train Acc: 0.6930 | Val Loss: 0.7954 | Val Acc: 0.6879



Validation: 100%|██████████| 60/60 [00:01<00:00, 57.38batch/s]


Epoch 5/20 | Train Loss: 0.7437 | Train Acc: 0.7171 | Val Loss: 0.7514 | Val Acc: 0.7089



Validation: 100%|██████████| 60/60 [00:00<00:00, 64.98batch/s]


Epoch 6/20 | Train Loss: 0.6993 | Train Acc: 0.7380 | Val Loss: 0.7265 | Val Acc: 0.7198



Validation: 100%|██████████| 60/60 [00:00<00:00, 91.01batch/s]


Epoch 7/20 | Train Loss: 0.6638 | Train Acc: 0.7526 | Val Loss: 0.7082 | Val Acc: 0.7284



Validation: 100%|██████████| 60/60 [00:00<00:00, 87.80batch/s]


Epoch 8/20 | Train Loss: 0.6337 | Train Acc: 0.7656 | Val Loss: 0.7082 | Val Acc: 0.7348



Validation: 100%|██████████| 60/60 [00:00<00:00, 83.16batch/s]


Epoch 9/20 | Train Loss: 0.6074 | Train Acc: 0.7775 | Val Loss: 0.6902 | Val Acc: 0.7409



Validation: 100%|██████████| 60/60 [00:00<00:00, 93.19batch/s]


Epoch 10/20 | Train Loss: 0.5856 | Train Acc: 0.7862 | Val Loss: 0.6715 | Val Acc: 0.7463



Validation: 100%|██████████| 60/60 [00:00<00:00, 87.93batch/s]


Epoch 11/20 | Train Loss: 0.5639 | Train Acc: 0.7941 | Val Loss: 0.6741 | Val Acc: 0.7493



Validation: 100%|██████████| 60/60 [00:00<00:00, 90.96batch/s]


Epoch 12/20 | Train Loss: 0.5452 | Train Acc: 0.8019 | Val Loss: 0.6698 | Val Acc: 0.7505



Validation: 100%|██████████| 60/60 [00:00<00:00, 60.22batch/s]


Epoch 13/20 | Train Loss: 0.5277 | Train Acc: 0.8089 | Val Loss: 0.6613 | Val Acc: 0.7563



Validation: 100%|██████████| 60/60 [00:01<00:00, 56.22batch/s]


Epoch 14/20 | Train Loss: 0.5140 | Train Acc: 0.8142 | Val Loss: 0.6553 | Val Acc: 0.7621



Validation: 100%|██████████| 60/60 [00:00<00:00, 86.77batch/s]


Epoch 15/20 | Train Loss: 0.4985 | Train Acc: 0.8205 | Val Loss: 0.6551 | Val Acc: 0.7610



Validation: 100%|██████████| 60/60 [00:00<00:00, 89.89batch/s]


Epoch 16/20 | Train Loss: 0.4844 | Train Acc: 0.8262 | Val Loss: 0.6500 | Val Acc: 0.7647



Validation: 100%|██████████| 60/60 [00:00<00:00, 88.25batch/s]


Epoch 17/20 | Train Loss: 0.4714 | Train Acc: 0.8320 | Val Loss: 0.6555 | Val Acc: 0.7651



Validation: 100%|██████████| 60/60 [00:00<00:00, 88.95batch/s]


Epoch 18/20 | Train Loss: 0.4588 | Train Acc: 0.8356 | Val Loss: 0.6576 | Val Acc: 0.7654



Validation: 100%|██████████| 60/60 [00:00<00:00, 85.62batch/s]


Epoch 19/20 | Train Loss: 0.4479 | Train Acc: 0.8395 | Val Loss: 0.6593 | Val Acc: 0.7684



Validation: 100%|██████████| 60/60 [00:00<00:00, 89.27batch/s]

Epoch 20/20 | Train Loss: 0.4361 | Train Acc: 0.8447 | Val Loss: 0.6603 | Val Acc: 0.7662

Restored model to the best state based on validation loss.


In [ ]:
y_true, y_pred = model.eval()

Validation: 100%|██████████| 60/60 [00:00<00:00, 92.76batch/s]


In [ ]:
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

Precision: 0.7661
Recall: 0.7661
F1 Score: 0.7653
Akurasi: 0.7662
[[1314  288  140  157]
 [ 164 1450  140  146]
 [  79   92 1587  142]
 [ 148  115  166 1471]]


In [ ]:
model.FASTTEXT()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 60/60 [00:00<00:00, 77.67batch/s]


Epoch 1/20 | Train Loss: 1.3151 | Train Acc: 0.3701 | Val Loss: 1.1909 | Val Acc: 0.4798



Validation: 100%|██████████| 60/60 [00:00<00:00, 62.62batch/s]


Epoch 2/20 | Train Loss: 1.1245 | Train Acc: 0.5242 | Val Loss: 1.0543 | Val Acc: 0.5589



Validation: 100%|██████████| 60/60 [00:01<00:00, 57.96batch/s]


Epoch 3/20 | Train Loss: 0.9981 | Train Acc: 0.5980 | Val Loss: 0.9646 | Val Acc: 0.6123



Validation: 100%|██████████| 60/60 [00:00<00:00, 94.27batch/s]


Epoch 4/20 | Train Loss: 0.9089 | Train Acc: 0.6438 | Val Loss: 0.9041 | Val Acc: 0.6380



Validation: 100%|██████████| 60/60 [00:00<00:00, 95.21batch/s]


Epoch 5/20 | Train Loss: 0.8426 | Train Acc: 0.6759 | Val Loss: 0.8594 | Val Acc: 0.6625



Validation: 100%|██████████| 60/60 [00:00<00:00, 88.74batch/s]


Epoch 6/20 | Train Loss: 0.7883 | Train Acc: 0.7020 | Val Loss: 0.8257 | Val Acc: 0.6802



Validation: 100%|██████████| 60/60 [00:00<00:00, 94.52batch/s]


Epoch 7/20 | Train Loss: 0.7438 | Train Acc: 0.7228 | Val Loss: 0.7984 | Val Acc: 0.6948



Validation: 100%|██████████| 60/60 [00:00<00:00, 95.19batch/s]


Epoch 8/20 | Train Loss: 0.7074 | Train Acc: 0.7398 | Val Loss: 0.7728 | Val Acc: 0.7018



Validation: 100%|██████████| 60/60 [00:00<00:00, 98.67batch/s]


Epoch 9/20 | Train Loss: 0.6751 | Train Acc: 0.7536 | Val Loss: 0.7572 | Val Acc: 0.7097



Validation: 100%|██████████| 60/60 [00:00<00:00, 95.15batch/s]


Epoch 10/20 | Train Loss: 0.6477 | Train Acc: 0.7646 | Val Loss: 0.7394 | Val Acc: 0.7198



Validation: 100%|██████████| 60/60 [00:00<00:00, 85.73batch/s]


Epoch 11/20 | Train Loss: 0.6240 | Train Acc: 0.7746 | Val Loss: 0.7315 | Val Acc: 0.7267



Validation: 100%|██████████| 60/60 [00:00<00:00, 60.72batch/s]


Epoch 12/20 | Train Loss: 0.6009 | Train Acc: 0.7841 | Val Loss: 0.7214 | Val Acc: 0.7340



Validation: 100%|██████████| 60/60 [00:00<00:00, 60.48batch/s]


Epoch 13/20 | Train Loss: 0.5830 | Train Acc: 0.7919 | Val Loss: 0.7101 | Val Acc: 0.7380



Validation: 100%|██████████| 60/60 [00:00<00:00, 93.02batch/s]


Epoch 14/20 | Train Loss: 0.5636 | Train Acc: 0.7995 | Val Loss: 0.7019 | Val Acc: 0.7433



Validation: 100%|██████████| 60/60 [00:00<00:00, 92.04batch/s]


Epoch 15/20 | Train Loss: 0.5476 | Train Acc: 0.8055 | Val Loss: 0.7003 | Val Acc: 0.7456



Validation: 100%|██████████| 60/60 [00:00<00:00, 94.99batch/s]


Epoch 16/20 | Train Loss: 0.5329 | Train Acc: 0.8115 | Val Loss: 0.6972 | Val Acc: 0.7465



Validation: 100%|██████████| 60/60 [00:00<00:00, 91.19batch/s]


Epoch 17/20 | Train Loss: 0.5192 | Train Acc: 0.8171 | Val Loss: 0.6887 | Val Acc: 0.7494



Validation: 100%|██████████| 60/60 [00:00<00:00, 94.57batch/s]


Epoch 18/20 | Train Loss: 0.5058 | Train Acc: 0.8222 | Val Loss: 0.6880 | Val Acc: 0.7527



Validation: 100%|██████████| 60/60 [00:00<00:00, 91.40batch/s]


Epoch 19/20 | Train Loss: 0.4955 | Train Acc: 0.8258 | Val Loss: 0.6871 | Val Acc: 0.7546



Validation: 100%|██████████| 60/60 [00:00<00:00, 98.13batch/s]

Epoch 20/20 | Train Loss: 0.4828 | Train Acc: 0.8309 | Val Loss: 0.6890 | Val Acc: 0.7560

Restored model to the best state based on validation loss.


In [ ]:
y_true, y_pred = model.eval()

Validation: 100%|██████████| 60/60 [00:00<00:00, 98.21batch/s]


In [ ]:
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

Precision: 0.7554
Recall: 0.7560
F1 Score: 0.7555
Akurasi: 0.7560
[[1320  293  127  159]
 [ 193 1399  142  166]
 [ 114  110 1563  113]
 [ 168  115  154 1463]]


In [ ]:
model = CreateModel(X_train, y_train,
                 X_test, y_test,
                 batch=BATCH_SIZE,
                 seq=SEQUENCE_LENGTH,
                 embedding_dim=EMBED_DIM,
                 n_layers=N_LAYERS,
                 dropout_rate=DROPOUT_RATE,
                 num_classes=NUM_CLASSES)

Loading setup data ...
Loading train data ...
Loading val data ...
Successful load model


In [18]:
model.TRANSFORMER(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 60/60 [00:00<00:00, 69.12batch/s]


Epoch 1/20 | Train Loss: 1.3242 | Train Acc: 0.3685 | Val Loss: 1.2452 | Val Acc: 0.4481



Validation: 100%|██████████| 60/60 [00:00<00:00, 67.00batch/s]


Epoch 2/20 | Train Loss: 1.1487 | Train Acc: 0.5101 | Val Loss: 1.0914 | Val Acc: 0.5517



Validation: 100%|██████████| 60/60 [00:00<00:00, 65.20batch/s]


Epoch 3/20 | Train Loss: 1.0064 | Train Acc: 0.5916 | Val Loss: 0.9909 | Val Acc: 0.6039



Validation: 100%|██████████| 60/60 [00:01<00:00, 44.80batch/s]


Epoch 4/20 | Train Loss: 0.9069 | Train Acc: 0.6411 | Val Loss: 0.9212 | Val Acc: 0.6376



Validation: 100%|██████████| 60/60 [00:00<00:00, 67.42batch/s]


Epoch 5/20 | Train Loss: 0.8345 | Train Acc: 0.6766 | Val Loss: 0.8711 | Val Acc: 0.6636



Validation: 100%|██████████| 60/60 [00:00<00:00, 70.13batch/s]


Epoch 6/20 | Train Loss: 0.7769 | Train Acc: 0.7024 | Val Loss: 0.8315 | Val Acc: 0.6846



Validation: 100%|██████████| 60/60 [00:00<00:00, 70.68batch/s]


Epoch 7/20 | Train Loss: 0.7324 | Train Acc: 0.7211 | Val Loss: 0.8034 | Val Acc: 0.6923



Validation: 100%|██████████| 60/60 [00:01<00:00, 52.18batch/s]


Epoch 8/20 | Train Loss: 0.6946 | Train Acc: 0.7371 | Val Loss: 0.7775 | Val Acc: 0.7065



Validation: 100%|██████████| 60/60 [00:00<00:00, 66.46batch/s]


Epoch 9/20 | Train Loss: 0.6632 | Train Acc: 0.7512 | Val Loss: 0.7586 | Val Acc: 0.7177



Validation: 100%|██████████| 60/60 [00:00<00:00, 69.53batch/s]


Epoch 10/20 | Train Loss: 0.6347 | Train Acc: 0.7632 | Val Loss: 0.7382 | Val Acc: 0.7260



Validation: 100%|██████████| 60/60 [00:01<00:00, 44.47batch/s]


Epoch 11/20 | Train Loss: 0.6138 | Train Acc: 0.7712 | Val Loss: 0.7278 | Val Acc: 0.7339



Validation: 100%|██████████| 60/60 [00:00<00:00, 69.13batch/s]


Epoch 12/20 | Train Loss: 0.5920 | Train Acc: 0.7789 | Val Loss: 0.7168 | Val Acc: 0.7335



Validation: 100%|██████████| 60/60 [00:00<00:00, 66.71batch/s]


Epoch 13/20 | Train Loss: 0.5736 | Train Acc: 0.7875 | Val Loss: 0.7141 | Val Acc: 0.7385



Validation: 100%|██████████| 60/60 [00:00<00:00, 68.03batch/s]


Epoch 14/20 | Train Loss: 0.5580 | Train Acc: 0.7939 | Val Loss: 0.7032 | Val Acc: 0.7410



Validation: 100%|██████████| 60/60 [00:01<00:00, 42.61batch/s]


Epoch 15/20 | Train Loss: 0.5417 | Train Acc: 0.7991 | Val Loss: 0.6957 | Val Acc: 0.7489



Validation: 100%|██████████| 60/60 [00:00<00:00, 68.06batch/s]


Epoch 16/20 | Train Loss: 0.5282 | Train Acc: 0.8035 | Val Loss: 0.6960 | Val Acc: 0.7446



Validation: 100%|██████████| 60/60 [00:00<00:00, 67.68batch/s]


Epoch 17/20 | Train Loss: 0.5170 | Train Acc: 0.8082 | Val Loss: 0.6900 | Val Acc: 0.7473



Validation: 100%|██████████| 60/60 [00:00<00:00, 69.77batch/s]


Epoch 18/20 | Train Loss: 0.5045 | Train Acc: 0.8137 | Val Loss: 0.6845 | Val Acc: 0.7525



Validation: 100%|██████████| 60/60 [00:01<00:00, 47.30batch/s]


Epoch 19/20 | Train Loss: 0.4942 | Train Acc: 0.8180 | Val Loss: 0.6809 | Val Acc: 0.7556



Validation: 100%|██████████| 60/60 [00:00<00:00, 68.72batch/s]

Epoch 20/20 | Train Loss: 0.4850 | Train Acc: 0.8207 | Val Loss: 0.6831 | Val Acc: 0.7555

Restored model to the best state based on validation loss.


In [19]:
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

Precision: 0.7554
Recall: 0.7560
F1 Score: 0.7555
Akurasi: 0.7560
[[1320  293  127  159]
 [ 193 1399  142  166]
 [ 114  110 1563  113]
 [ 168  115  154 1463]]


In [20]:
model.BERT(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 60/60 [00:00<00:00, 70.86batch/s]


Epoch 1/20 | Train Loss: 1.3548 | Train Acc: 0.3308 | Val Loss: 1.2974 | Val Acc: 0.3974



Validation: 100%|██████████| 60/60 [00:00<00:00, 70.67batch/s]


Epoch 2/20 | Train Loss: 1.2132 | Train Acc: 0.4626 | Val Loss: 1.1445 | Val Acc: 0.5032



Validation: 100%|██████████| 60/60 [00:01<00:00, 47.09batch/s]


Epoch 3/20 | Train Loss: 1.0713 | Train Acc: 0.5529 | Val Loss: 1.0394 | Val Acc: 0.5717



Validation: 100%|██████████| 60/60 [00:00<00:00, 66.92batch/s]


Epoch 4/20 | Train Loss: 0.9704 | Train Acc: 0.6059 | Val Loss: 0.9668 | Val Acc: 0.6110



Validation: 100%|██████████| 60/60 [00:00<00:00, 67.76batch/s]


Epoch 5/20 | Train Loss: 0.8949 | Train Acc: 0.6440 | Val Loss: 0.9194 | Val Acc: 0.6309



Validation: 100%|██████████| 60/60 [00:00<00:00, 65.59batch/s]


Epoch 6/20 | Train Loss: 0.8407 | Train Acc: 0.6725 | Val Loss: 0.8688 | Val Acc: 0.6654



Validation: 100%|██████████| 60/60 [00:01<00:00, 45.87batch/s]


Epoch 7/20 | Train Loss: 0.7922 | Train Acc: 0.6932 | Val Loss: 0.8383 | Val Acc: 0.6748



Validation: 100%|██████████| 60/60 [00:00<00:00, 69.12batch/s]


Epoch 8/20 | Train Loss: 0.7551 | Train Acc: 0.7104 | Val Loss: 0.8091 | Val Acc: 0.6880



Validation: 100%|██████████| 60/60 [00:00<00:00, 68.17batch/s]


Epoch 9/20 | Train Loss: 0.7235 | Train Acc: 0.7244 | Val Loss: 0.7853 | Val Acc: 0.6969



Validation: 100%|██████████| 60/60 [00:00<00:00, 71.84batch/s]


Epoch 10/20 | Train Loss: 0.6956 | Train Acc: 0.7372 | Val Loss: 0.7713 | Val Acc: 0.7118



Validation: 100%|██████████| 60/60 [00:01<00:00, 46.92batch/s]


Epoch 11/20 | Train Loss: 0.6720 | Train Acc: 0.7463 | Val Loss: 0.7545 | Val Acc: 0.7194



Validation: 100%|██████████| 60/60 [00:00<00:00, 69.81batch/s]


Epoch 12/20 | Train Loss: 0.6503 | Train Acc: 0.7550 | Val Loss: 0.7597 | Val Acc: 0.7169



Validation: 100%|██████████| 60/60 [00:00<00:00, 72.71batch/s]


Epoch 13/20 | Train Loss: 0.6320 | Train Acc: 0.7631 | Val Loss: 0.7434 | Val Acc: 0.7210



Validation: 100%|██████████| 60/60 [00:00<00:00, 70.87batch/s]


Epoch 14/20 | Train Loss: 0.6151 | Train Acc: 0.7697 | Val Loss: 0.7253 | Val Acc: 0.7297



Validation: 100%|██████████| 60/60 [00:01<00:00, 46.45batch/s]


Epoch 15/20 | Train Loss: 0.6006 | Train Acc: 0.7763 | Val Loss: 0.7218 | Val Acc: 0.7319



Validation: 100%|██████████| 60/60 [00:00<00:00, 71.42batch/s]


Epoch 16/20 | Train Loss: 0.5850 | Train Acc: 0.7824 | Val Loss: 0.7029 | Val Acc: 0.7372



Validation: 100%|██████████| 60/60 [00:00<00:00, 71.23batch/s]


Epoch 17/20 | Train Loss: 0.5723 | Train Acc: 0.7874 | Val Loss: 0.7047 | Val Acc: 0.7364



Validation: 100%|██████████| 60/60 [00:00<00:00, 60.62batch/s]


Epoch 18/20 | Train Loss: 0.5608 | Train Acc: 0.7918 | Val Loss: 0.7054 | Val Acc: 0.7389



Validation: 100%|██████████| 60/60 [00:00<00:00, 61.30batch/s]


Epoch 19/20 | Train Loss: 0.5482 | Train Acc: 0.7973 | Val Loss: 0.7041 | Val Acc: 0.7423



Validation: 100%|██████████| 60/60 [00:00<00:00, 70.04batch/s]

Epoch 20/20 | Train Loss: 0.5390 | Train Acc: 0.8006 | Val Loss: 0.6895 | Val Acc: 0.7451

Restored model to the best state based on validation loss.


In [21]:
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

Precision: 0.7554
Recall: 0.7560
F1 Score: 0.7555
Akurasi: 0.7560
[[1320  293  127  159]
 [ 193 1399  142  166]
 [ 114  110 1563  113]
 [ 168  115  154 1463]]


# Evaluasi

In [ ]:
import time

# Mencatat waktu untuk model GRU
start_time = time.time()
model.GRU()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)
y_true, y_pred = model.eval()
gru_time = time.time() - start_time

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print("=== GRU Results ===")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")
print(f"Total Computation Time: {gru_time:.2f} seconds")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

# Mencatat waktu untuk model FASTTEXT
start_time = time.time()
model.FASTTEXT()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)
y_true, y_pred = model.eval()
fasttext_time = time.time() - start_time

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print("=== FASTTEXT Results ===")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")
print(f"Total Computation Time: {fasttext_time:.2f} seconds")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

# Mencatat waktu untuk model TRANSFORMER
start_time = time.time()
model.TRANSFORMER(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)
y_true, y_pred = model.eval()
transformer_time = time.time() - start_time

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print("=== TRANSFORMER Results ===")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")
print(f"Total Computation Time: {transformer_time:.2f} seconds")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

# Mencatat waktu untuk model BERT
start_time = time.time()
model.BERT(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)
y_true, y_pred = model.eval()
bert_time = time.time() - start_time

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print("=== BERT Results ===")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")
print(f"Total Computation Time: {bert_time:.2f} seconds")

matriks = confusion_matrix(y_true, y_pred)
print(matriks)

Validation: 100%|██████████| 60/60 [00:00<00:00, 61.61batch/s]


Epoch 1/20 | Train Loss: 1.2480 | Train Acc: 0.4259 | Val Loss: 1.0895 | Val Acc: 0.5390



Validation: 100%|██████████| 60/60 [00:00<00:00, 67.22batch/s]


Epoch 2/20 | Train Loss: 1.0055 | Train Acc: 0.5870 | Val Loss: 0.9271 | Val Acc: 0.6306



Validation: 100%|██████████| 60/60 [00:00<00:00, 85.12batch/s]


Epoch 3/20 | Train Loss: 0.8826 | Train Acc: 0.6520 | Val Loss: 0.8429 | Val Acc: 0.6665



Validation: 100%|██████████| 60/60 [00:00<00:00, 86.05batch/s]


Epoch 4/20 | Train Loss: 0.8041 | Train Acc: 0.6888 | Val Loss: 0.7956 | Val Acc: 0.6871



Validation: 100%|██████████| 60/60 [00:00<00:00, 86.67batch/s]


Epoch 5/20 | Train Loss: 0.7470 | Train Acc: 0.7157 | Val Loss: 0.7600 | Val Acc: 0.7036



Validation: 100%|██████████| 60/60 [00:00<00:00, 85.27batch/s]


Epoch 6/20 | Train Loss: 0.7030 | Train Acc: 0.7351 | Val Loss: 0.7349 | Val Acc: 0.7142



Validation: 100%|██████████| 60/60 [00:00<00:00, 90.49batch/s]


Epoch 7/20 | Train Loss: 0.6670 | Train Acc: 0.7509 | Val Loss: 0.7210 | Val Acc: 0.7250



Validation: 100%|██████████| 60/60 [00:00<00:00, 64.13batch/s]


Epoch 8/20 | Train Loss: 0.6366 | Train Acc: 0.7636 | Val Loss: 0.7047 | Val Acc: 0.7326



Validation: 100%|██████████| 60/60 [00:00<00:00, 62.99batch/s]


Epoch 9/20 | Train Loss: 0.6078 | Train Acc: 0.7765 | Val Loss: 0.6923 | Val Acc: 0.7356



Validation: 100%|██████████| 60/60 [00:00<00:00, 68.17batch/s]


Epoch 10/20 | Train Loss: 0.5847 | Train Acc: 0.7853 | Val Loss: 0.6796 | Val Acc: 0.7412



Validation: 100%|██████████| 60/60 [00:00<00:00, 88.03batch/s]


Epoch 11/20 | Train Loss: 0.5630 | Train Acc: 0.7951 | Val Loss: 0.6770 | Val Acc: 0.7455



Validation: 100%|██████████| 60/60 [00:00<00:00, 92.28batch/s]


Epoch 12/20 | Train Loss: 0.5441 | Train Acc: 0.8017 | Val Loss: 0.6754 | Val Acc: 0.7489



Validation: 100%|██████████| 60/60 [00:00<00:00, 85.68batch/s]


Epoch 13/20 | Train Loss: 0.5277 | Train Acc: 0.8088 | Val Loss: 0.6638 | Val Acc: 0.7544



Validation: 100%|██████████| 60/60 [00:00<00:00, 90.16batch/s]


Epoch 14/20 | Train Loss: 0.5118 | Train Acc: 0.8140 | Val Loss: 0.6617 | Val Acc: 0.7568



Validation: 100%|██████████| 60/60 [00:00<00:00, 86.59batch/s]


Epoch 15/20 | Train Loss: 0.4960 | Train Acc: 0.8211 | Val Loss: 0.6557 | Val Acc: 0.7609



Validation: 100%|██████████| 60/60 [00:00<00:00, 65.10batch/s]


Epoch 16/20 | Train Loss: 0.4827 | Train Acc: 0.8264 | Val Loss: 0.6618 | Val Acc: 0.7622



Validation: 100%|██████████| 60/60 [00:01<00:00, 58.29batch/s]


Epoch 17/20 | Train Loss: 0.4709 | Train Acc: 0.8321 | Val Loss: 0.6592 | Val Acc: 0.7600



Validation: 100%|██████████| 60/60 [00:00<00:00, 91.66batch/s]


Epoch 18/20 | Train Loss: 0.4572 | Train Acc: 0.8360 | Val Loss: 0.6629 | Val Acc: 0.7642



Validation: 100%|██████████| 60/60 [00:00<00:00, 86.74batch/s]


Epoch 19/20 | Train Loss: 0.4435 | Train Acc: 0.8418 | Val Loss: 0.6592 | Val Acc: 0.7650



Training:  49%|████▉     | 464/938 [00:07<00:07, 65.94batch/s]